services:
  swarmauri-com:
    build: .
    container_name: swarmauri-com
    restart: unless-stopped
    labels:
      site.host: swarmauri.com
      site.kind: mdwrk-lander
    expose:
      - "80"
