import { LayerInfo, FamilyInfo, MaturityInfo } from "../types";

// Generated by scripts/generate-package-catalog.mjs from swarmauri-sdk/pkgs.
// Do not hand-edit package summary data; refresh from the SDK package index instead.
export const SDK_METADATA = {
  "version": "0.9.1.dev6",
  "versionPackage": "swarmauri",
  "monorepoVersion": "0.6.2.dev3",
  "pythonSupport": ">=3.10,<3.15",
  "totalWorkspaceMemberEntries": 310,
  "totalWorkspaceMembers": 310,
  "totalIndexedRecords": 337,
  "workspaceBackedIndexedRecords": 310,
  "duplicateWorkspaceMembers": [],
  "lastGenerated": "2026-06-30T17:56:43.035Z",
  "source": "swarmauri-sdk/pkgs/package-index.toml"
};

export const LAYERS: LayerInfo[] = [
  {
    "id": "00-typing",
    "name": "00-Typing Utility Layer",
    "count": 1,
    "meaning": "typing helpers and generic type composition primitives",
    "description": "typing helpers and generic type composition primitives"
  },
  {
    "id": "10-interfaces",
    "name": "10-Interfaces Contract Layer",
    "count": 1,
    "meaning": "interface and protocol contracts",
    "description": "interface and protocol contracts"
  },
  {
    "id": "20-bases",
    "name": "20-Base Behavior Layer",
    "count": 1,
    "meaning": "reusable base classes, mixins, and component models",
    "description": "reusable base classes, mixins, and component models"
  },
  {
    "id": "30-standard-kernel",
    "name": "30-Standard Kernel Layer",
    "count": 1,
    "meaning": "bundled first-party standard component kernel",
    "description": "bundled first-party standard component kernel"
  },
  {
    "id": "40-standards",
    "name": "40-Standards Split First-Party Layer",
    "count": 181,
    "meaning": "first-party split standard packages",
    "description": "first-party split standard packages"
  },
  {
    "id": "50-community",
    "name": "50-Community Provider Layer",
    "count": 106,
    "meaning": "community and provider-specific packages",
    "description": "community and provider-specific packages"
  },
  {
    "id": "60-plugins",
    "name": "60-Plugin Extension Layer",
    "count": 5,
    "meaning": "plugin packages and plugin examples",
    "description": "plugin packages and plugin examples"
  },
  {
    "id": "70-experimental",
    "name": "70-Experimental Incubator Layer",
    "count": 36,
    "meaning": "incubating and planning-stage packages",
    "description": "incubating and planning-stage packages"
  },
  {
    "id": "80-facades",
    "name": "80-Facade Namespace Layer",
    "count": 1,
    "meaning": "aggregate user-facing facade packages",
    "description": "aggregate user-facing facade packages"
  },
  {
    "id": "90-deprecated",
    "name": "90-Deprecated Compatibility Layer",
    "count": 4,
    "meaning": "deprecated compatibility packages",
    "description": "deprecated compatibility packages"
  }
];

export const FAMILIES: FamilyInfo[] = [
  {
    "name": "tool",
    "count": 43,
    "description": "Callable tools that agents and workflows can execute."
  },
  {
    "name": "middleware",
    "count": 19,
    "description": "Middleware that wraps execution boundaries for security, policy, logging, or transport behavior."
  },
  {
    "name": "cipher_suite",
    "count": 18,
    "description": "Standards-oriented cryptographic cipher-suite profiles."
  },
  {
    "name": "llm",
    "count": 17,
    "description": "Large-language-model provider adapters and inference integrations."
  },
  {
    "name": "signing",
    "count": 17,
    "description": "Digital-signature generation and verification packages."
  },
  {
    "name": "transport",
    "count": 15,
    "description": "Network and process transports for serialized payloads."
  },
  {
    "name": "certs",
    "count": 13,
    "description": "Certificate creation, verification, and certificate-authority helpers."
  },
  {
    "name": "vectorstore",
    "count": 13,
    "description": "Vector database and similarity-search storage integrations."
  },
  {
    "name": "auth_idp",
    "count": 12,
    "description": "Authentication, OAuth, OIDC, and identity-provider packages."
  },
  {
    "name": "distance",
    "count": 12,
    "description": "Distance and similarity calculations for vectors and structured data."
  },
  {
    "name": "keyprovider",
    "count": 10,
    "description": "Key management, key storage, and key-provider integrations."
  },
  {
    "name": "parser",
    "count": 10,
    "description": "Document, text, and structured-data parser packages."
  },
  {
    "name": "tokens",
    "count": 10,
    "description": "Token issuance, validation, rotation, and binding helpers."
  },
  {
    "name": "billing",
    "count": 9,
    "description": "Billing, payment, quota, and account-metering integrations."
  },
  {
    "name": "crypto",
    "count": 8,
    "description": "Cryptographic primitives, envelopes, and encryption adapters."
  },
  {
    "name": "storage",
    "count": 8,
    "description": "Persistent storage adapters for files, object stores, and release assets."
  },
  {
    "name": "xmp",
    "count": 8,
    "description": "Extensible Metadata Platform encoders and metadata helpers."
  },
  {
    "name": "certservice",
    "count": 5,
    "description": "Certificate-service integrations backed by cloud or enterprise providers."
  },
  {
    "name": "evaluator",
    "count": 5,
    "description": "Evaluation checks for code, behavior, safety, or usage constraints."
  },
  {
    "name": "mre_crypto",
    "count": 5,
    "description": "Multi-recipient encryption and key-wrapping components."
  },
  {
    "name": "embedding",
    "count": 4,
    "description": "Embedding model and feature-vector generation components."
  },
  {
    "name": "gitfilter",
    "count": 4,
    "description": "Git filter and repository-backed storage helpers."
  },
  {
    "name": "skills",
    "count": 4,
    "description": "Skill packages and skill-execution surfaces."
  },
  {
    "name": "tests",
    "count": 4,
    "description": "Testing and validation helper packages."
  },
  {
    "name": "toolkit",
    "count": 4,
    "description": "Grouped tool and runtime toolkit packages."
  },
  {
    "name": "example",
    "count": 3,
    "description": "Example packages used to document package structure and extension patterns."
  },
  {
    "name": "pop",
    "count": 3,
    "description": "Proof-of-possession token and credential helpers."
  },
  {
    "name": "publisher",
    "count": 3,
    "description": "Message publishing and webhook/event output integrations."
  },
  {
    "name": "layout",
    "count": 2,
    "description": "Layout and rendering-oriented package experiments."
  },
  {
    "name": "measurement",
    "count": 2,
    "description": "Measurement and aggregate metric utilities."
  },
  {
    "name": "metric",
    "count": 2,
    "description": "Metric implementations for model, data, or vector behavior."
  },
  {
    "name": "6w",
    "count": 1,
    "description": "Swarmauri 6w package family."
  },
  {
    "name": "6x",
    "count": 1,
    "description": "Swarmauri 6x package family."
  },
  {
    "name": "6y",
    "count": 1,
    "description": "Swarmauri 6y package family."
  },
  {
    "name": "6z",
    "count": 1,
    "description": "Swarmauri 6z package family."
  },
  {
    "name": "77",
    "count": 1,
    "description": "Swarmauri 77 package family."
  },
  {
    "name": "9x",
    "count": 1,
    "description": "Swarmauri 9x package family."
  },
  {
    "name": "agents",
    "count": 1,
    "description": "Agent orchestration and task-execution components."
  },
  {
    "name": "bases",
    "count": 1,
    "description": "Reusable base implementations and component behavior."
  },
  {
    "name": "canon",
    "count": 1,
    "description": "Swarmauri canon package family."
  },
  {
    "name": "catoml",
    "count": 1,
    "description": "Swarmauri catoml package family."
  },
  {
    "name": "cayaml",
    "count": 1,
    "description": "Swarmauri cayaml package family."
  },
  {
    "name": "distancemetrics",
    "count": 1,
    "description": "Swarmauri distancemetrics package family."
  },
  {
    "name": "documentstore",
    "count": 1,
    "description": "Swarmauri documentstore package family."
  },
  {
    "name": "embeddedsigner",
    "count": 1,
    "description": "Swarmauri embeddedsigner package family."
  },
  {
    "name": "embedxmp",
    "count": 1,
    "description": "Swarmauri embedxmp package family."
  },
  {
    "name": "evaluatorpool",
    "count": 1,
    "description": "Grouped evaluator execution components."
  },
  {
    "name": "experimental",
    "count": 1,
    "description": "Swarmauri experimental package family."
  },
  {
    "name": "facade",
    "count": 1,
    "description": "Aggregate user-facing namespace or facade package."
  },
  {
    "name": "fasttokenizer",
    "count": 1,
    "description": "Swarmauri fasttokenizer package family."
  },
  {
    "name": "g9",
    "count": 1,
    "description": "Swarmauri g9 package family."
  },
  {
    "name": "indexbuilder",
    "count": 1,
    "description": "Swarmauri indexbuilder package family."
  },
  {
    "name": "interfaces",
    "count": 1,
    "description": "Interface and protocol contracts."
  },
  {
    "name": "jaml",
    "count": 1,
    "description": "Swarmauri jaml package family."
  },
  {
    "name": "jz",
    "count": 1,
    "description": "Swarmauri jz package family."
  },
  {
    "name": "keyproviders",
    "count": 1,
    "description": "Key-provider integrations and compatibility surfaces."
  },
  {
    "name": "matrix",
    "count": 1,
    "description": "Swarmauri matrix package family."
  },
  {
    "name": "mediasigner",
    "count": 1,
    "description": "Swarmauri mediasigner package family."
  },
  {
    "name": "monotone",
    "count": 1,
    "description": "Swarmauri monotone package family."
  },
  {
    "name": "mto",
    "count": 1,
    "description": "Swarmauri mto package family."
  },
  {
    "name": "ocr",
    "count": 1,
    "description": "Optical character recognition components."
  },
  {
    "name": "prompt",
    "count": 1,
    "description": "Prompt-template and prompt-rendering components."
  },
  {
    "name": "ptree",
    "count": 1,
    "description": "Swarmauri ptree package family."
  },
  {
    "name": "queryengine",
    "count": 1,
    "description": "Swarmauri queryengine package family."
  },
  {
    "name": "s.f",
    "count": 1,
    "description": "Swarmauri s.f package family."
  },
  {
    "name": "sfw",
    "count": 1,
    "description": "Swarmauri sfw package family."
  },
  {
    "name": "snt",
    "count": 1,
    "description": "Swarmauri snt package family."
  },
  {
    "name": "standard-kernel",
    "count": 1,
    "description": "Bundled first-party standard component kernel."
  },
  {
    "name": "state",
    "count": 1,
    "description": "Swarmauri state package family."
  },
  {
    "name": "tigr",
    "count": 1,
    "description": "Swarmauri tigr package family."
  },
  {
    "name": "typing",
    "count": 1,
    "description": "Typing helpers and generic type-composition primitives."
  },
  {
    "name": "workflow",
    "count": 1,
    "description": "Swarmauri workflow package family."
  },
  {
    "name": "ye",
    "count": 1,
    "description": "Swarmauri ye package family."
  },
  {
    "name": "ymls",
    "count": 1,
    "description": "Swarmauri ymls package family."
  },
  {
    "name": "zdx",
    "count": 1,
    "description": "Swarmauri zdx package family."
  },
  {
    "name": "zr0",
    "count": 1,
    "description": "Swarmauri zr0 package family."
  }
];

export const COMPONENT_FAMILIES: FamilyInfo[] = [
  {
    "name": "tool",
    "count": 60,
    "description": "Callable tools that agents and workflows can execute."
  },
  {
    "name": "llm",
    "count": 47,
    "description": "Large-language-model provider adapters and inference integrations."
  },
  {
    "name": "distance",
    "count": 23,
    "description": "Distance and similarity calculations for vectors and structured data."
  },
  {
    "name": "middleware",
    "count": 19,
    "description": "Middleware that wraps execution boundaries for security, policy, logging, or transport behavior."
  },
  {
    "name": "cipher_suite",
    "count": 18,
    "description": "Standards-oriented cryptographic cipher-suite profiles."
  },
  {
    "name": "parser",
    "count": 18,
    "description": "Document, text, and structured-data parser packages."
  },
  {
    "name": "signing",
    "count": 17,
    "description": "Digital-signature generation and verification packages."
  },
  {
    "name": "transport",
    "count": 16,
    "description": "Network and process transports for serialized payloads."
  },
  {
    "name": "vectorstore",
    "count": 14,
    "description": "Vector database and similarity-search storage integrations."
  },
  {
    "name": "measurement",
    "count": 13,
    "description": "Measurement and aggregate metric utilities."
  },
  {
    "name": "auth_idp",
    "count": 12,
    "description": "Authentication, OAuth, OIDC, and identity-provider packages."
  },
  {
    "name": "certs",
    "count": 12,
    "description": "Certificate creation, verification, and certificate-authority helpers."
  },
  {
    "name": "logger_handler",
    "count": 12,
    "description": "Swarmauri logger handler components."
  },
  {
    "name": "logger_formatter",
    "count": 11,
    "description": "Swarmauri logger formatter components."
  },
  {
    "name": "metric",
    "count": 11,
    "description": "Metric implementations for model, data, or vector behavior."
  },
  {
    "name": "keyprovider",
    "count": 10,
    "description": "Key management, key storage, and key-provider integrations."
  },
  {
    "name": "similarity",
    "count": 10,
    "description": "Swarmauri similarity components."
  },
  {
    "name": "tokens",
    "count": 10,
    "description": "Token issuance, validation, rotation, and binding helpers."
  },
  {
    "name": "billing",
    "count": 9,
    "description": "Billing, payment, quota, and account-metering integrations."
  },
  {
    "name": "embedding",
    "count": 9,
    "description": "Embedding model and feature-vector generation components."
  },
  {
    "name": "inner_product",
    "count": 8,
    "description": "Swarmauri inner product components."
  },
  {
    "name": "storage",
    "count": 8,
    "description": "Persistent storage adapters for files, object stores, and release assets."
  },
  {
    "name": "tool_llm",
    "count": 8,
    "description": "Swarmauri tool llm components."
  },
  {
    "name": "xmp",
    "count": 8,
    "description": "Extensible Metadata Platform encoders and metadata helpers."
  },
  {
    "name": "crypto",
    "count": 7,
    "description": "Cryptographic primitives, envelopes, and encryption adapters."
  },
  {
    "name": "message",
    "count": 7,
    "description": "Swarmauri message components."
  },
  {
    "name": "schema_converter",
    "count": 7,
    "description": "Swarmauri schema converter components."
  },
  {
    "name": "norm",
    "count": 6,
    "description": "Swarmauri norm components."
  },
  {
    "name": "seminorm",
    "count": 6,
    "description": "Swarmauri seminorm components."
  },
  {
    "name": "toolkit",
    "count": 6,
    "description": "Grouped tool and runtime toolkit packages."
  },
  {
    "name": "agents",
    "count": 5,
    "description": "Agent orchestration and task-execution components."
  },
  {
    "name": "certservice",
    "count": 5,
    "description": "Certificate-service integrations backed by cloud or enterprise providers."
  },
  {
    "name": "chunker",
    "count": 5,
    "description": "Swarmauri chunker components."
  },
  {
    "name": "evaluator",
    "count": 5,
    "description": "Evaluation checks for code, behavior, safety, or usage constraints."
  },
  {
    "name": "image_gen",
    "count": 5,
    "description": "Swarmauri image gen components."
  },
  {
    "name": "mre_crypto",
    "count": 5,
    "description": "Multi-recipient encryption and key-wrapping components."
  },
  {
    "name": "pseudometric",
    "count": 5,
    "description": "Swarmauri pseudometric components."
  },
  {
    "name": "chain",
    "count": 4,
    "description": "Swarmauri chain components."
  },
  {
    "name": "conversation",
    "count": 4,
    "description": "Swarmauri conversation components."
  },
  {
    "name": "gitfilter",
    "count": 4,
    "description": "Git filter and repository-backed storage helpers."
  },
  {
    "name": "prompt",
    "count": 4,
    "description": "Prompt-template and prompt-rendering components."
  },
  {
    "name": "skills",
    "count": 4,
    "description": "Skill packages and skill-execution surfaces."
  },
  {
    "name": "tracing",
    "count": 4,
    "description": "Swarmauri tracing components."
  },
  {
    "name": "example",
    "count": 3,
    "description": "Example packages used to document package structure and extension patterns."
  },
  {
    "name": "pop",
    "count": 3,
    "description": "Proof-of-possession token and credential helpers."
  },
  {
    "name": "publisher",
    "count": 3,
    "description": "Message publishing and webhook/event output integrations."
  },
  {
    "name": "stt",
    "count": 3,
    "description": "Swarmauri stt components."
  },
  {
    "name": "tts",
    "count": 3,
    "description": "Swarmauri tts components."
  },
  {
    "name": "vlm",
    "count": 3,
    "description": "Swarmauri vlm components."
  },
  {
    "name": "evaluatorpool",
    "count": 2,
    "description": "Grouped evaluator execution components."
  },
  {
    "name": "dataconnector",
    "count": 1,
    "description": "Swarmauri dataconnector components."
  },
  {
    "name": "document",
    "count": 1,
    "description": "Swarmauri document components."
  },
  {
    "name": "embeddedsigner",
    "count": 1,
    "description": "Swarmauri embeddedsigner components."
  },
  {
    "name": "embedxmp",
    "count": 1,
    "description": "Swarmauri embedxmp components."
  },
  {
    "name": "evaluator_result",
    "count": 1,
    "description": "Swarmauri evaluator result components."
  },
  {
    "name": "keyproviders",
    "count": 1,
    "description": "Key-provider integrations and compatibility surfaces."
  },
  {
    "name": "logger",
    "count": 1,
    "description": "Swarmauri logger components."
  },
  {
    "name": "matrix",
    "count": 1,
    "description": "Swarmauri matrix components."
  },
  {
    "name": "mediasigner",
    "count": 1,
    "description": "Swarmauri mediasigner components."
  },
  {
    "name": "ocr",
    "count": 1,
    "description": "Optical character recognition components."
  },
  {
    "name": "pipeline",
    "count": 1,
    "description": "Swarmauri pipeline components."
  },
  {
    "name": "prompt_template",
    "count": 1,
    "description": "Swarmauri prompt template components."
  },
  {
    "name": "rate_limit",
    "count": 1,
    "description": "Swarmauri rate limit components."
  },
  {
    "name": "service_registry",
    "count": 1,
    "description": "Swarmauri service registry components."
  },
  {
    "name": "state",
    "count": 1,
    "description": "Swarmauri state components."
  },
  {
    "name": "swarm",
    "count": 1,
    "description": "Swarmauri swarm components."
  },
  {
    "name": "task_mgmt_strategy",
    "count": 1,
    "description": "Swarmauri task mgmt strategy components."
  },
  {
    "name": "tests",
    "count": 1,
    "description": "Testing and validation helper packages."
  },
  {
    "name": "vector",
    "count": 1,
    "description": "Swarmauri vector components."
  },
  {
    "name": "zdx",
    "count": 1,
    "description": "Swarmauri zdx components."
  }
];

export const MATURITIES: MaturityInfo[] = [
  {
    "name": "standard",
    "count": 181,
    "description": "First-party standards-oriented package."
  },
  {
    "name": "community",
    "count": 106,
    "description": "Community or provider-specific integration package."
  },
  {
    "name": "experimental",
    "count": 36,
    "description": "Incubating or planning-stage package."
  },
  {
    "name": "plugin",
    "count": 5,
    "description": "Plugin or extension package."
  },
  {
    "name": "deprecated",
    "count": 4,
    "description": "Compatibility package retained for older usage."
  },
  {
    "name": "foundation",
    "count": 3,
    "description": "Foundational package used by the SDK architecture."
  },
  {
    "name": "facade",
    "count": 1,
    "description": "Aggregate user-facing facade package."
  },
  {
    "name": "standard-kernel",
    "count": 1,
    "description": "Bundled first-party standard component kernel."
  }
];
